name: average-aqi-cicd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # deploy-data-analyzer:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 7.0.x
  #     - run: cd applications/dataanalyzer
  #     - name: Restore dependencies
  #       run: dotnet restore
  #     - name: Build
  #       run: dotnet build --no-restore
  #     - name: Test
  #       run: dotnet test --no-build --verbosity normal
  #     - name: Deploy
  #     - uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{secrets.HEROKU_DATA_ANALYZER_NAME}}
  #         heroku_email: ${{secrets.HEROKU_EMAIL}}
  #         buildpack: https://github.com/jincod/dotnetcore-buildpack
  # deploy-data-collector:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 7.0.x
  #     - run: cd applications/datacollector
  #     - name: Restore dependencies
  #       run: dotnet restore
  #     - name: Build
  #       run: dotnet build --no-restore
  #     - name: Test
  #       run: dotnet test --no-build --verbosity normal
  #     - name: Deploy
  #     - uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: ${{secrets.HEROKU_DATA_COLLECTOR_NAME}}
  #         heroku_email: ${{secrets.HEROKU_EMAIL}}
  #         buildpack: https://github.com/jincod/dotnetcore-buildpack
  test-and-deploy-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: applications/webapp/test
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_WEB_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: applications/webapp/src
          # healthcheck: "https://webapp-averageaqi.herokuapp.com//health"
